# Supported algorithms:
# "chacha20-poly1305" (The account password length must be 32 bytes)
# "aes-256-gcm"       (The account password length must be 32 bytes)
# "aes-192-gcm"       (The account password length must be 24 bytes)
# "aes-128-gcm"       (The account password length must be 16 bytes)
cryptoAlgorithm = "chacha20-poly1305"

# The gordafarid authentication on the server-side
credentials = [
    { username = "ZZA", password = "password000000000000000000000ZZA" },
    { username = "xyz", password = "00000000000000000000000000000xyz" },
]

[server]
address = "127.0.0.1:9090"
hashSalt = "salt"          # (Must be same in the both client and server) (OPTIONAL)

# Timeout settings (OPTIONAL)
[timeout]
dialTimeout = 1000                # In seconds
gordafaridHandshakeTimeout = 1000 # In seconds
