# cryptographic algorithm for encryption
# supported algorithms:
# "chacha20-poly1305" (the account password length must be 32 bytes)
# "aes-256-gcm" (the account password length must be 32 bytes)
# "aes-192-gcm" (the account password length must be 24 bytes)
# "aes-128-gcm" (the account password length must be 16 bytes)
cryptoAlgorithm = "chacha20-poly1305"

# The gordafarid authentication on the server-side
credentials = [
    { username = "ZZA", password = "password000000000000000000000ZZA" },
    { username = "xyz", password = "00000000000000000000000000000xyz" },
]

[server]
address = "127.0.0.1:9090"


[timeout]
dialTimeout = 1000                # In seconds
gordafaridHandshakeTimeout = 1000 # In seconds
