# cryptographic algorithm for encryption
# supported algorithms:
# "chacha20-poly1305" (password length must be 32 bytes)
# "aes-256-gcm" (password length must be 32 bytes)
# "aes-192-gcm" (password length must be 24 bytes)
# "aes-128-gcm" (password length must be 16 bytes)
cryptoAlgorithm = "chacha20-poly1305"

# server-side authentication
credentials = [
    { username = "user1", password = "00000000000000000000000000000000" },
    { username = "user2", password = "00000000000000000000000000000001" },
    { username = "user3", password = "00000000000000000000000000000002" },
]

[server]
address = "127.0.0.1:9090"


[timeout]
dialTimeout = 1000                # In seconds
gordafaridHandshakeTimeout = 1000 # In seconds
