[client]
address = "127.0.0.1:8080"

[server]
address = "127.0.0.1:9090"

[crypto]
# supported algorithms:
# "aes-256-gcm" (password length must be 32 bytes)
# "aes-192-gcm" (password length must be 24 bytes)
# "aes-128-gcm" (password length must be 16 bytes)
algorithm = "chacha20-poly1305"
password = "00000000000000000000000000000000"

# In seconds
dialtimeout = 10
handshakeTimeout = 10 # Unused in client mode