# supported algorithms:
# "chacha20-poly1305" (password length must be 32 bytes)
# "aes-256-gcm" (password length must be 32 bytes)
# "aes-192-gcm" (password length must be 24 bytes)
# "aes-128-gcm" (password length must be 16 bytes)
cryptoAlgorithm = "chacha20-poly1305"

# Authentication
[account]
username = "user1"
password = "00000000000000000000000000000000" # (must satisfy the specified algorithm key length)

[client]
address = "127.0.0.1:8080"

[server]
address = "127.0.0.1:9090"

# SOCKS5 username/password authentication
[socks5Credentials]
user1 = "user1p"
user2 = "user2p"
user3 = "user3p"

# timeout settings
[timeout]
dialTimeout = 1000             # In seconds
socks5HandshakeTimeout = 10000 # In seconds
