# supported algorithms:
# "chacha20-poly1305" (the account password length must be 32 bytes)
# "aes-256-gcm" (the account password length must be 32 bytes)
# "aes-192-gcm" (the account password length must be 24 bytes)
# "aes-128-gcm" (the account password length must be 16 bytes)
cryptoAlgorithm = "chacha20-poly1305"

# Authentication
[account]
username = "ZZA"
password = "password000000000000000000000ZZA" # (must satisfy the specified algorithm key length)

[client]
address = "127.0.0.1:8080"

[server]
address = "127.0.0.1:9090"

# SOCKS5 username/password authentication on the client-side
[socks5Credentials]
userZZA = "ZZA"
userNIKA = "NIKAPassword"

# timeout settings
[timeout]
dialTimeout = 1000             # In seconds
socks5HandshakeTimeout = 10000 # In seconds
