[client]
address = "127.0.0.1:8080"

[server]
address = "127.0.0.1:9090"

[crypto]
# supported algorithms:
# "chacha20-poly1305" (password length must be 32 bytes)
# "aes-256-gcm" (password length must be 32 bytes)
# "aes-192-gcm" (password length must be 24 bytes)
# "aes-128-gcm" (password length must be 16 bytes)
algorithm = "chacha20-poly1305"
password = "00000000000000000000000000000000"

[timeout]
dialTimeout = 1000 # In seconds
socks5HandshakeTimeout = 10000 # In seconds (unused in client mode)
socks5ValidationTimeout = 10000000000 # In milliseconds (unused in server mode)


[credentials] # username/password for SOCKS5 authentication (unused in client mode)
user1 = "user1p"
user2 = "user2p"
user3 = "user3p"