# Supported algorithms:
# "chacha20-poly1305" (The account password length must be 32 bytes)
# "aes-256-gcm"       (The account password length must be 32 bytes)
# "aes-192-gcm"       (The account password length must be 24 bytes)
# "aes-128-gcm"       (The account password length must be 16 bytes)
cryptoAlgorithm = "chacha20-poly1305"

# Authentication
[account]
username = "ZZA"
password = "password000000000000000000000ZZA" # Must satisfy the specified algorithm key length

[client]
address = "127.0.0.1:8080"
hashSalt = "salt"          # Must be same in the both client and server (OPTIONAL)

[server]
address = "127.0.0.1:9090"

# SOCKS5 username/password authentication on the client-side (OPTIONAL)
[socks5Credentials]
userZZA = "ZZA"
userNIKA = "NIKAPassword"

# Timeout settings (OPTIONAL)
[timeout]
dialTimeout = 1000             # In seconds
socks5HandshakeTimeout = 10000 # In seconds
